package main;

import java.util.Hashtable;

public class CardDirectory {

	public Hashtable<Integer, String> CardDirectory() {
		Hashtable<Integer, String> cardDetails = new Hashtable<Integer, String>();
		cardDetails.put(1, "Goblin Shaman");
		cardDetails.put(2, "Giant Roc");
		cardDetails.put(3, "Kobold Miner");
		cardDetails.put(4, "Fire Beetle");
		cardDetails.put(5, "Malric Inferno");
		cardDetails.put(6, "Serpentine Soldier");
		cardDetails.put(7, "Pit Ogre");
		cardDetails.put(8, "Cerberus");
		cardDetails.put(9, "Fire Demon");
		cardDetails.put(10, "Serpent of the Flame");
		cardDetails.put(11, "Elemental Phoenix");
		cardDetails.put(12, "Pirate Captain");
		cardDetails.put(13, "Spineback Turtle");
		cardDetails.put(14, "Crustacean King");
		cardDetails.put(15, "Sabre Shark");
		cardDetails.put(16, "Alric Stormbringer");
		cardDetails.put(17, "Medusa");
		cardDetails.put(18, "Water Elemental");
		cardDetails.put(19, "Frozen Soldier");
		cardDetails.put(20, "Mischievous Mermaid");
		cardDetails.put(21, "Naga Warrior");
		cardDetails.put(22, "Frost Giant");
		cardDetails.put(23, "Flesh Golem");
		cardDetails.put(24, "Goblin Sorcerer");
		cardDetails.put(25, "Rexxie");
		cardDetails.put(26, "Minotaur Warrior");
		cardDetails.put(27, "Lyanna Natura");
		cardDetails.put(28, "Earth Elemental");
		cardDetails.put(29, "Stone Golem");
		cardDetails.put(30, "Stonesplitter Orc");
		cardDetails.put(31, "Magi of the Forest");
		cardDetails.put(32, "Swamp Thing");
		cardDetails.put(33, "Spirit of the Forest");
		cardDetails.put(34, "Divine Healer");
		cardDetails.put(35, "Feral Spirit");
		cardDetails.put(36, "Silvershield Knight");
		cardDetails.put(37, "Silvershield Warrior");
		cardDetails.put(38, "Tyrus Paladium");
		cardDetails.put(39, "Peacebringer");
		cardDetails.put(40, "Silvershield Paladin");
		cardDetails.put(41, "Clay Golem");
		cardDetails.put(42, "Defender of Truth");
		cardDetails.put(43, "Air Elemental");
		cardDetails.put(44, "Angel of Light");
		cardDetails.put(45, "Animated Corpse");
		cardDetails.put(46, "Haunted Spider");
		cardDetails.put(47, "Skeleton Assassin");
		cardDetails.put(48, "Spineback Wolf");
		cardDetails.put(49, "Zintar Mortalis");
		cardDetails.put(50, "Haunted Spirit");
		cardDetails.put(51, "Twisted Jester");
		cardDetails.put(52, "Undead Priest");
		cardDetails.put(53, "Dark Enchantress");
		cardDetails.put(54, "Screaming Banshee");
		cardDetails.put(55, "Lord of Darkness");
		cardDetails.put(56, "Selenia Sky");
		cardDetails.put(57, "Lightning Dragon");
		cardDetails.put(58, "Chromatic Dragon");
		cardDetails.put(59, "Gold Dragon");
		cardDetails.put(60, "Peaceful Giant");
		cardDetails.put(61, "Grumpy Dwarf");
		cardDetails.put(62, "Elven Cutthroat");
		cardDetails.put(63, "Centaur");
		cardDetails.put(64, "Cocatrice");
		cardDetails.put(65, "Cyclops");
		cardDetails.put(66, "Enchanted Pixie");
		cardDetails.put(67, "Raging Impaler");
		cardDetails.put(68, "Magi Sphinx");
		cardDetails.put(69, "Hydra");
		cardDetails.put(70, "Talia Firestorm");
		cardDetails.put(71, "Xia Seachan");
		cardDetails.put(72, "Xander Foxwood");
		cardDetails.put(73, "Kiara Lightbringer");
		cardDetails.put(74, "Jarlax the Undead");
		cardDetails.put(75, "Dragon Whelp");
		cardDetails.put(76, "Royal Dragon Archer");
		cardDetails.put(77, "Shin-Lo");
		cardDetails.put(78, "Neb Seni");
		cardDetails.put(79, "Highland Archer");
		cardDetails.put(80, "Rusty Android");
		cardDetails.put(81, "Hobgoblin");
		cardDetails.put(82, "Lord Arianthus");
		cardDetails.put(83, "Sea Genie");
		cardDetails.put(84, "Divine Sorceress");
		cardDetails.put(85, "Mushroom Seer");
		cardDetails.put(86, "Vampire");
		cardDetails.put(87, "Flame Imp");
		cardDetails.put(88, "Daria Dragonscale");
		cardDetails.put(89, "Sacred Unicorn");
		cardDetails.put(90, "Wood Nymph");
		cardDetails.put(91, "Creeping Ooze");
		cardDetails.put(92, "Phantom Soldier");
		cardDetails.put(93, "Pirate Archer");
		cardDetails.put(94, "Naga Fire Wizard");
		cardDetails.put(95, "Brownie");
		cardDetails.put(96, "Silvershield Archers");
		cardDetails.put(97, "Goblin Mech");
		cardDetails.put(98, "Ruler of the Seas");
		cardDetails.put(99, "Skeletal Warrior");
		cardDetails.put(100, "Imp Bowman");
		cardDetails.put(101, "Crystal Werewolf");
		cardDetails.put(102, "Javelin Thrower");
		cardDetails.put(103, "Sea Monster");
		cardDetails.put(104, "Prismatic Energy");
		cardDetails.put(105, "Undead Minotaur");
		cardDetails.put(106, "Exploding Dwarf");
		cardDetails.put(107, "Manticore");
		cardDetails.put(108, "Black Dragon");
		cardDetails.put(109, "Crypt Mancer");
		cardDetails.put(110, "Plado Emberstorm");
		cardDetails.put(111, "Valnamor");
		cardDetails.put(112, "Prince Rennyn");
		cardDetails.put(113, "The Peakrider");
		cardDetails.put(114, "Delwyn Dragonscale");
		cardDetails.put(115, "Dragonling Bowman");
		cardDetails.put(116, "Fiendish Harpy");
		cardDetails.put(117, "Red Dragon");
		cardDetails.put(118, "Armorsmith");
		cardDetails.put(119, "Silvershield Bard");
		cardDetails.put(120, "Goblin Chef");
		cardDetails.put(121, "Minotaur Warlord");
		cardDetails.put(122, "Electric Eels");
		cardDetails.put(123, "Mermaid Healer");
		cardDetails.put(124, "Undead Archer");
		cardDetails.put(125, "Corrupted Pegasus");
		cardDetails.put(126, "Molten Ogre");
		cardDetails.put(127, "Lord of Fire");
		cardDetails.put(128, "Enchanted Defender");
		cardDetails.put(129, "Dwarven Wizard");
		cardDetails.put(130, "Archmage Arius");
		cardDetails.put(131, "Furious Chicken");
		cardDetails.put(132, "Fallen Specter");
		cardDetails.put(133, "Beetle Queen");
		cardDetails.put(134, "Naga Windmaster");
		cardDetails.put(135, "Maggots");
		cardDetails.put(136, "Cursed Slimeball");
		cardDetails.put(137, "Giant Scorpion");
		cardDetails.put(138, "Undead Badger");
		cardDetails.put(139, "Dark Astronomer");
		cardDetails.put(140, "Bone Golem");
		cardDetails.put(141, "Death Elemental");
		cardDetails.put(142, "Soulstorm");
		cardDetails.put(143, "Darkest Mage");
		cardDetails.put(144, "Dark Ha'on");
		cardDetails.put(145, "Contessa L'ament");
		cardDetails.put(146, "Cave Slug");
		cardDetails.put(147, "Crystal Jaguar");
		cardDetails.put(148, "Lone Boatman");
		cardDetails.put(149, "Herbalist");
		cardDetails.put(150, "Truthspeaker");
		cardDetails.put(151, "Luminous Eagle");
		cardDetails.put(152, "Shieldbearer");
		cardDetails.put(153, "Light Elemental");
		cardDetails.put(154, "Thunderbird");
		cardDetails.put(155, "High Priest Darius");
		cardDetails.put(156, "Mother Khala");
		cardDetails.put(157, "Kobold Bruiser");
		cardDetails.put(158, "Serpentine Spy");
		cardDetails.put(159, "Magma Troll");
		cardDetails.put(160, "Goblin Fireballer");
		cardDetails.put(161, "Fire Elemental");
		cardDetails.put(162, "Living Lava");
		cardDetails.put(163, "Spark Pixies");
		cardDetails.put(164, "Ferexia General");
		cardDetails.put(165, "Pyromaniac");
		cardDetails.put(166, "Magnor");
		cardDetails.put(167, "Pyre");
		cardDetails.put(168, "Feasting Seaweed");
		cardDetails.put(169, "Albatross");
		cardDetails.put(170, "Tortisian Fighter");
		cardDetails.put(171, "Sniping Narwhal");
		cardDetails.put(172, "Ice Pixie");
		cardDetails.put(173, "Giant Squid");
		cardDetails.put(174, "Serpent of Eld");
		cardDetails.put(175, "Coral Wraith");
		cardDetails.put(176, "Azmare Harpoonist");
		cardDetails.put(177, "Phantom of the Abyss");
		cardDetails.put(178, "Bortus");
		cardDetails.put(179, "Goblin Thief");
		cardDetails.put(180, "Failed Summoner");
		cardDetails.put(181, "Biceratops");
		cardDetails.put(182, "Orc Sergeant");
		cardDetails.put(183, "Khmer Princess");
		cardDetails.put(184, "Unicorn Mustang");
		cardDetails.put(185, "Child of the Forest");
		cardDetails.put(186, "Mitica Headhunter");
		cardDetails.put(187, "Sporcerer");
		cardDetails.put(188, "Kron the Undying");
		cardDetails.put(189, "Wizard of Eastwood");
		cardDetails.put(190, "Elven Defender");
		cardDetails.put(191, "Horny Toad");
		cardDetails.put(192, "Mantoid");
		cardDetails.put(193, "Parasitic Growth");
		cardDetails.put(194, "Elven Mystic");
		cardDetails.put(195, "Goblin Chariot");
		cardDetails.put(196, "Tower Griffin");
		cardDetails.put(197, "War Chaang");
		cardDetails.put(198, "Tortisian Chief");
		cardDetails.put(199, "Cornealus");
		cardDetails.put(200, "Camila Sungazer");
		cardDetails.put(201, "The Vigilator");
		cardDetails.put(202, "Scale Doctor");
		cardDetails.put(203, "Dragon Jumper");
		cardDetails.put(204, "Gloridax Magus");
		cardDetails.put(205, "Prince Julian");
		cardDetails.put(206, "Boogeyman");
		cardDetails.put(207, "Spirit Miner");
		cardDetails.put(208, "Battle Orca");
		cardDetails.put(209, "Chain Golem");
		cardDetails.put(210, "Diamond Dragon");
		cardDetails.put(211, "Gloridax Guardian");
		cardDetails.put(212, "Fire Spitter");
		cardDetails.put(213, "The Kraken");
		cardDetails.put(214, "Ettin Spearman");
		cardDetails.put(215, "Octopider");
		cardDetails.put(216, "Silvershield Assassin");
		cardDetails.put(217, "Baby Unicorn");
		cardDetails.put(218, "Gelatinous Cube");
		cardDetails.put(219, "Gremlin Blaster");
		cardDetails.put(220, "Screeching Vulture");
		cardDetails.put(221, "Spirit Shaman");
		cardDetails.put(222, "Zalran Efreet");
		cardDetails.put(223, "Serpentine Mystic");
		cardDetails.put(224, "Drake of Arnak");
		cardDetails.put(225, "Barking Spider");
		cardDetails.put(226, "Nectar Queen");
		cardDetails.put(227, "Flame Monkey");
		cardDetails.put(228, "Pyromancer");
		cardDetails.put(229, "Undead Rexx");
		cardDetails.put(230, "Shadowy Presence");
		cardDetails.put(231, "Torhilo the Frozen");
		cardDetails.put(232, "Wave Runner");
		cardDetails.put(233, "Warrior of Peace");
		cardDetails.put(234, "Evangelist");
		cardDetails.put(235, "Mimosa Nightshade");
		cardDetails.put(236, "Yodin Zaku");
		cardDetails.put(237, "Halfling Alchemist");
		cardDetails.put(238, "Mighty Dricken");
		cardDetails.put(239, "Chanseus the Great");
		cardDetails.put(240, "Kretch Tallevor");
		cardDetails.put(241, "Onyx Sentinel");
		cardDetails.put(242, "Sand Worm");
		cardDetails.put(243, "Silvershield Sheriff");
		cardDetails.put(244, "Bila the Radiant");
		cardDetails.put(245, "Grim Reaper");
		cardDetails.put(246, "Phantasm");
		cardDetails.put(247, "Fineas Rage");
		cardDetails.put(248, "Ant Miners");
		cardDetails.put(249, "Spirit Druid Grog");
		cardDetails.put(250, "Captain's Ghost");
		cardDetails.put(251, "Kelp Initiate");
		cardDetails.put(252, "Gloridax Soldier");
		cardDetails.put(253, "Centauri Mage");
		cardDetails.put(254, "Lir Deepswimmer");
		cardDetails.put(255, "Robo-Dragon Knight");
		cardDetails.put(256, "Ancient Lich");
		cardDetails.put(257, "Vera Salacia");
		cardDetails.put(258, "Owster Rotwell");
		cardDetails.put(259, "Mylor Crowling");
		cardDetails.put(260, "Qid Yuff");
		cardDetails.put(261, "Lorna Shine");
		cardDetails.put(262, "Brighton Bloom");
		cardDetails.put(263, "Poseidon");
		cardDetails.put(264, "Frost Lion");
		cardDetails.put(265, "Caladuum");
		cardDetails.put(266, "Flamesmith");
		cardDetails.put(267, "Cthulhu");
		cardDetails.put(268, "Marrow's Ghost");
		cardDetails.put(269, "Kralus");
		cardDetails.put(270, "Lunakari Mistress");
		cardDetails.put(271, "Oaken Behemoth");
		cardDetails.put(272, "Goblin Dartling");
		cardDetails.put(273, "Battering Ram");
		cardDetails.put(274, "Naga Brute");
		cardDetails.put(275, "Dragon Spirit");
		cardDetails.put(276, "Grenadier");
		cardDetails.put(277, "Lensmaster");
		cardDetails.put(278, "Scarred Llama Mage");
		cardDetails.put(279, "Beatrix Ironhand");
		cardDetails.put(280, "Axemaster");
		cardDetails.put(281, "Charlok Minotaur");
		cardDetails.put(282, "Dark Ferryman");
		cardDetails.put(283, "Chain Spinner");
		cardDetails.put(284, "Harvester");
		cardDetails.put(285, "Nightmare");
		cardDetails.put(286, "Almo Cambio");
		cardDetails.put(287, "Demented Shark");
		cardDetails.put(288, "Temple Priest");
		cardDetails.put(289, "Efreet Elder");
		cardDetails.put(290, "Theorosa Nightshade");
		cardDetails.put(291, "Byzantine Kitty");
		cardDetails.put(292, "Goblin Firemage");
		cardDetails.put(293, "Lobstradamus");
		cardDetails.put(294, "The Gorlodon");
		cardDetails.put(295, "Hero of Beyond");
		cardDetails.put(296, "Two Gun Pete");
		cardDetails.put(297, "Epona");
		cardDetails.put(298, "Aganju");
		cardDetails.put(299, "Chimney Wallstop");
		cardDetails.put(300, "Krash Wanderford");
		cardDetails.put(301, "Orella Abadon");
		cardDetails.put(302, "Sarius");
		cardDetails.put(303, "Gorth");
		cardDetails.put(304, "Fina Voxom");
		cardDetails.put(305, "Alva the Crusher");
		cardDetails.put(306, "Isgald Vorst");
		cardDetails.put(307, "Alfredo");
		cardDetails.put(308, "Relenor Cleaver");
		cardDetails.put(309, "Edith Emberstar");
		cardDetails.put(310, "Flagulon Reine");
		cardDetails.put(311, "Bertrol Gobson");
		cardDetails.put(312, "Katrelba Gobson");
		cardDetails.put(313, "Cutter Brieze");
		cardDetails.put(314, "Palidon Rakk");
		cardDetails.put(315, "Quora Towershead");
		cardDetails.put(316, "Jini Guise");
		cardDetails.put(317, "Helmet Kharafax");
		cardDetails.put(318, "Hugo Strongsword");
		cardDetails.put(319, "Ajax Lightfoot");
		cardDetails.put(320, "Captain Katie");
		cardDetails.put(321, "Marisol Contuma");
		cardDetails.put(322, "Sola Ranjell");
		cardDetails.put(323, "Whistling Damon");
		cardDetails.put(324, "Witch of Warwick");
		cardDetails.put(325, "Kotriphus Bayne");
		cardDetails.put(326, "Liza Fox");
		cardDetails.put(327, "Trapp Falloway");
		cardDetails.put(328, "Xulax Nightwind");
		cardDetails.put(329, "Larissa Kerato");
		cardDetails.put(330, "Tatiana Blayde");
		cardDetails.put(331, "Venari Heatsmith");
		cardDetails.put(332, "Exploding Rats");
		cardDetails.put(333, "Lava Launcher");
		cardDetails.put(334, "Pelacor Mercenary");
		cardDetails.put(335, "Venari Seedsmith");
		cardDetails.put(336, "Djinn Biljka");
		cardDetails.put(337, "Pelacor Bandit");
		cardDetails.put(338, "Venari Wavesmith");
		cardDetails.put(339, "Djinn Oshannus");
		cardDetails.put(340, "Pelacor Deceiver");
		cardDetails.put(341, "Venari Bonesmith");
		cardDetails.put(342, "Harklaw");
		cardDetails.put(343, "Pelacor Conjurer");
		cardDetails.put(344, "Venari Crystalsmith");
		cardDetails.put(345, "Djinn Renova");
		cardDetails.put(346, "Naga Assassin");
		cardDetails.put(347, "Twilight Basilisk");
		cardDetails.put(348, "Djinn Chwala");
		cardDetails.put(349, "Gargoya Lion");
		cardDetails.put(350, "Gargoya Devil");
		cardDetails.put(351, "Uraeus");

		return cardDetails;
	}

}
